version: '3.3'

services:

  nginx-reverse-proxy:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

  rps-app:
    image: edekargaurav88/rockpaperscissors:0.0.1
    container_name: rps-app
    depends_on:
      - nginx-reverse-proxy
    ports:
      - 8080
      - 8081