version: '3.3'

services:

  nginx-reverse-proxy:
    image: nginx:1.17
    container_name: nginx-reverse-proxy
    depends_on:
      - rps-app-server
    volumes:
      - './docker_resources/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - 80:80

  rps-app-server:
    image: edekargaurav88/rockpaperscissors:0.0.1
    container_name: rps-app-server